language: python
python:
  - "3.6.6"
services:
  - postgresql
env:
  global:
    - DB_NAME='test_flask'
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - "psql -c 'create database test_flask;' -U postgres"
# command to run tests
script: 
  - nosetests --with-coverage --cover-tests
  - coverage report

after_success:
  - coveralls